### ISSUE TITLE
Notification accent color showing up incorrectly

### ISSUE THREAD

**Issue by zstecker** [Swrve/swrve-android-sdk#286]
I'm using `swrve-firebase` v6.1.0, and I'm noticing that the notification accent color I set via `SwrveNotificationConfig.Builder` is not showing up correctly in my notifications. 

From looking at the source code, it seems that `SwrveNotificationConfig` expects a color _resource ID_, while `SwrveNotificationBuilder` expects an actual color int:
https://github.com/Swrve/swrve-android-sdk/blob/bbc23a74be03a99442207b1d507e76ba6239d1ff/SwrveSDKCommon/src/main/java/com/swrve/sdk/SwrveNotificationBuilder.java#L63
https://github.com/Swrve/swrve-android-sdk/blob/bbc23a74be03a99442207b1d507e76ba6239d1ff/SwrveSDKCommon/src/main/java/com/swrve/sdk/SwrveNotificationBuilder.java#L97-L99

Line 98 should use `ContextCompat.getColor()` to get the color from the resource ID. This issue was raised in https://github.com/Swrve/swrve-android-sdk/issues/124 in 2016, but it seems that the issue has returned.

I would be glad to provide additional information if it would be helpful. Thanks!

**Comment by davidbreenwex** [comment]
Hi @zstecker, thanks for bringing this to our attention. 
We'll fix this in our next release which is due next week. 

In the meantime if you need a fix immediately you can workaround the issue by changing how you set the accentColorResourceID in the SwrveNotificationConfig.Builder when initializing Swrve.

Basically you need to set the accentColorResourceId with an actual aarrggbb color integer instead of a resource id as follows:

```
SwrveNotificationConfig.Builder notificationConfig = new SwrveNotificationConfig.Builder(R.drawable.logo1, R.drawable.logo2, channel)
   .activityClass(MainActivity.class)
   .largeIconDrawableId(R.drawable.swrve_s_solid)
   .accentColorResourceId(ContextCompat.getColor(context, R.color.orange));
```

I'll let you know once the fix is released.

**Comment by davidbreenwex** [comment]
Hi @zstecker,

We have just released a new version which addresses this issue.
https://github.com/Swrve/swrve-android-sdk/releases/tag/6.1.1

Thanks again for reporting the issue.
