### ISSUE TITLE
App ID issue - Authentication Failed

### ISSUE THREAD

**Issue by ahmednawaz22** [Swrve/swrve-android-sdk#303]
Hi there,

I'm using App ID and API Key from Swrve Dashboard , but still I'm getting this error
` E/SwrveSDK: Error sending events to Swrve. responseCode: 403	responseBody:{"code":403,"message":"Authentication failed - invalid app ID '****'."}`

And Swrve Dashboard still saying 0 User.
Your Kind Support required here,

thanks!

**Comment by davidbreenwex** [comment]
Hi @ahmednawaz22 

This is usually caused by pointing at the wrong Swrve Stack.
From the app_id I can see you should be pointing at the SwrveEU stack in the SwrveConfig when initializing Swrve. 
Can you try that and let me know if it fixes the issue?

If not, it's probably best to open a support ticket by emailing support@swrve.com

Best,
David

**Comment by ahmednawaz22** [comment]
Hi David,

Thanks for your support,
that issue has been resolved.
But I have a strange situation ; there is no user (0 Users ) on My Swrve Dashboard.

My devices are not visible on QA Device list too and I add devices manually using userID but still I cannot see any logs.

please provide support at your earliest as I have a planned demo with my Client.

Thanks

**Comment by davidbreenwex** [comment]
Hi @ahmednawaz22, 

Please create a support ticket by emailing support@swrve.com and we can arrange a call to debug the issue over a screenshare. 

Best, 
David
